### ISSUE TITLE
Standalone plan hardcoded to only use 'z1' for AZ

### ISSUE THREAD

**Issue by elric392** [blacksmith-community/redis-forge-boshrelease#4]
Trying to use this bosh release, and ran into issue with the availability zones configuration.

snippet from bosh manifest:
> b-redis-cache:
>               type:    standalone
>               vm_type: t2.small
>               network: dynamic-services
>               azs: [us-east-1a, us-east-1c, us-east-1e]

But the 'azs' params are not being honored. Regardless, the 'manifest' when creating a service, on that plan, always uses 'z1'.

**Comment by jhunt** [comment]
`azs` is not a valid property for the standalone plan.  As a workaround, you can set your cloud-config on your Blacksmith broker such that `z1` is in AWS' `us-east-1c`.

However, there is still value in making it configurable for cases where you want to run multiple services in different zones.  Indeed, the clustered redis topology also hard-codes it's availability zones to `[z1, z2`] which might also be undesirable.
